name: attendance_nmscst
description: "Flutter Web for Admin"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # HIGH PRIO
  intl: ^0.19.0

  # STATE MANAGEMENT
  provider: ^6.1.2

  # FIREBASE
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4

  # NETWORK
  # http: ^1.2.2
  http: ^0.13.6
  web_socket_channel: ^3.0.1

  # STORAGE
  shared_preferences: ^2.3.2

  # DOCUMENTS
  printing: ^5.5.0
  pdf: ^3.6.0

  # STYLING
  hexcolor: ^3.0.1
  lottie: ^2.7.0

  # GOOGLE MAPS
  google_maps_flutter: ^2.6.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.1
  google_api_headers: ^1.1.1
  location: ^5.0.3
  geolocator: ^9.0.2
  geocoding: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/img/
  - assets/json/
